version: '3.3'

services:

    ost:
        image: openspeedtest/latest
        container_name: openspeedtest
#        volumes:  #opcional
#            - ./ost_docker/:/etc/ssl/  #opcional
        ports:
            - '8200:3000'
            - '8300:3001'
        restart: unless-stopped

        
